table Reseller
	lineageTag: edccdd7a-3841-4dda-8b54-abb17451286e

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: 82cb408f-fb7b-4870-8fff-826365f1b51f
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column 'Reseller ID'
		dataType: string
		lineageTag: 2826a655-b9eb-4b4c-8bab-6babd8bd94eb
		summarizeBy: none
		sourceColumn: Reseller ID

		annotation SummarizationSetBy = Automatic

	column 'Business Type'
		dataType: string
		lineageTag: 392dea66-08da-49dd-a180-0d29d4386a39
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

	column Reseller
		dataType: string
		lineageTag: c25d75e7-82f7-46db-9e64-63d3a0b81d00
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e992a29f-2360-4ee0-81d6-4624e2b944e5
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: 12c1c4a3-7144-43a8-9d86-76b29aaa1835
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: cf36b713-7d28-4a70-baa8-0a2f5f8770e4
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 4e242353-4652-48a0-bb16-9b3d29820744
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Reseller = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\91771\Downloads\GSPBI25 - Sales.xlsx"), null, true),
				    Reseller_Table = Source{[Item="Reseller",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Reseller_Table,{{"ResellerKey", Int64.Type}, {"Reseller ID", type text}, {"Business Type", type text}, {"Reseller", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1)
				in
				    #"Removed Top Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

