table SalesTerritory
	lineageTag: b3a42fd4-889a-4984-b7f2-74bf53cf511b

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 29c983f4-283a-455f-8c19-8111af647d86
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 397f1305-d5da-47f4-be66-e925bba44cda
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 31c9508b-ee8b-4b62-b592-009c7860c73e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: 042ddb8d-e139-41e0-96c4-a8d4842b203f
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	partition SalesTerritory = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\91771\Downloads\GSPBI25 - Sales.xlsx"), null, true),
				    SalesTerritory_Table = Source{[Item="SalesTerritory",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(SalesTerritory_Table,{{"SalesTerritoryKey", Int64.Type}, {"Region", type text}, {"Country", type text}, {"Group", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

